#10 Task
name: New CI\CD

on:
  push:
    branches:
      - 'test-stage'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
#          ansible-galaxy install -r requirements.yml
      - name: Deploy Docker container with Ansible
        run: |
          ansible-playbook IT-Course/playbook.yml
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          ANSIBLE_HOST_KEY_CHECKING: false
        